# Projet d'analyse sur les jeux vidéos avec Steam

## Questions métier
1. Quels genres dominent le catalogue, et leur part évolue-t-elle dans le temps ?
2. Les jeux Indie sont-ils moins chers que les autres ?
3. Les réductions sont-elles plus fréquentes sur certains genres ?
4. Plus de langues supportées = de meilleurs avis ?
5. Combien de jeux sortent par mois ?

## Lien Kaggle
Kaggle : https://www.kaggle.com/datasets/trolukovich/steam-games-complete-dataset

## Licence
CC0: Public Domain

## 1. Import de mon Dataset 

J'ai importé mon jeu de données avec la bibliothèque Pandas.

In [ ]:
import pandas as pd
df = pd.read_csv("../data/raw/steam_games.csv")

## 2. Taille de mon Dataset 
Cette commande ci-dessous affichera le nombre de lignes et de colonnes au total, issu de mon jeu de données.

In [2]:
df.shape

(40833, 20)

## 3. Aperçu de mon Dataset 

Ensuite, j'affiche les aperçus de mon jeu de données avec la commande ci dessous.
On peut y retrouver les caractéristiques de mon jeu de données ci-joint.

In [3]:
df.head()

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN
3,https://store.steampowered.com/app/221100/DayZ/,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...","Dec 13, 2018",Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...",NaN,"Action,Adventure,Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99,NaN
4,https://store.steampowered.com/app/8500/EVE_On...,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...","May 6, 2003",CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French",NaN,"Action,Free to Play,Massively Multiplayer,RPG,...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free,NaN

## 4. Aperçu des types et des valeurs non nulles 
Ici, une seule colonne est numérique (`achievements`, float). Les 19 autres sont du texte. Aucune colonne n'est complète, sauf `url`. Les prix et les dates devront être convertis

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40833 entries, 0 to 40832
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   url                       40833 non-null  str
 1   types                     40831 non-null  str
 2   name                      40817 non-null  str
 3   desc_snippet              27612 non-null  str
 4   recent_reviews            2706 non-null   str
 5   all_reviews               28470 non-null  str
 6   release_date              37654 non-null  str
 7   developer                 40490 non-null  str
 8   publisher                 35733 non-null  str
 9   popular_tags              37888 non-null  str
 10  game_details              40313 non-null  str
 11  languages                 40797 non-null  str
 12  achievements              12194 non-null  float64
 13  genre                     40395 non-null  str
 14  game_description          37920 non-null  str
 15  mature_content            2897 non-null   str
 16  minimum_requirements      21069 non-null  str
 17  recommended_requirements  21075 non-null  str
 18  original_price            35522 non-null  str
 19  discount_price            14543 non-null  str
dtypes: float64(1), str(19)
memory usage: 6.2 MB

## 5.Aperçu des types mal choisis :
Ici on constate que :
- `original_price` et `discount_price` devraient être numériques, 
- `release_date` une date, `types` une catégorie, 
- `achievements` est un float alors que ce sont des entiers.

In [5]:
df.dtypes

url                             str
types                           str
name                            str
desc_snippet                    str
recent_reviews                  str
all_reviews                     str
release_date                    str
developer                       str
publisher                       str
popular_tags                    str
game_details                    str
languages                       str
achievements                float64
genre                           str
game_description                str
mature_content                  str
minimum_requirements            str
recommended_requirements        str
original_price                  str
discount_price                  str
dtype: object

## 6.Aperçu des valeurs manquantes :
Après l'exécution de ma commande voici les valeurs manquantes : 
- `recent_reviews` (38 127)
- `mature_content` (37 936)
- `achievements` (28 639)
- `discount_price` (26 290) 
- `original_price`(5 311) 
- `release_date` (3 179)

In [6]:
df.isna().sum()

url                             0
types                           2
name                           16
desc_snippet                13221
recent_reviews              38127
all_reviews                 12363
release_date                 3179
developer                     343
publisher                    5100
popular_tags                 2945
game_details                  520
languages                      36
achievements                28639
genre                         438
game_description             2913
mature_content              37936
minimum_requirements        19764
recommended_requirements    19758
original_price               5311
discount_price              26290
dtype: int64

## 7.Pourcentages des valeurs manquantes :

D'après la commande, on peut constater ces pourcentages ci-dessous :

- plus de 90 % : `recent_reviews` (93,4), `mature_content` (92,9)
- entre 60 et 70 % : `achievements` (70,1), `discount_price` (64,4)
- autour de 48 % : `minimum_requirements` et `recommended_requirements`
- entre 30 et 32 % : `desc_snippet` (32,4), `all_reviews` (30,3)
- moins de 13 % : `original_price` (13,0), `publisher` (12,5), `release_date` (7,8)

In [7]:
(df.isna().mean() * 100).round(1).sort_values(ascending=False)

recent_reviews              93.4
mature_content              92.9
achievements                70.1
discount_price              64.4
minimum_requirements        48.4
recommended_requirements    48.4
desc_snippet                32.4
all_reviews                 30.3
original_price              13.0
publisher                   12.5
release_date                 7.8
popular_tags                 7.2
game_description             7.1
game_details                 1.3
genre                        1.1
developer                    0.8
languages                    0.1
name                         0.0
url                          0.0
types                        0.0
dtype: float64

## 8.Nature des produits :

Ici nous voyons qu'il y a :

- 38 021 `app`,
- 2 572 `bundle`, 
- 238 `sub` et 2 valeurs manquantes.

Les bundles et subs sont des lots de jeux, pas des jeux.
On fera un choix dans mon notebook 2(nettoyage) si y a besoin de garder ou exclure et on justifiera nos choix.

In [8]:
df["types"].value_counts(dropna=False)

types
app       38021
bundle     2572
sub         238
NaN           2
Name: count, dtype: int64

## 9.Aperçu des doublons:

On voit 0 ligne entièrement dupliquée, mais 83 noms qui apparaissent plusieurs fois. 
Il faudra examiner les 83 noms avant de supprimer : la cause peut être un même jeu en plusieurs éditions.

In [9]:
df.duplicated().sum(), df["name"].duplicated().sum()

(np.int64(0), np.int64(83))

## 10.Affichage des Statistiques Numériques:

Ici, seule `achievements` est numérique.
Elle est renseignée pour 12 194 jeux seulement. La médiane est de 21 succès, la moyenne de 77 ainsi que le maximum est de 9 821. 
Cet écart entre la médiane et le maximum montre quelques valeurs extrêmes (149 jeux dépassent 1 000 succès). 
Elles seront examinées au nettoyage : elles peuvent être réelles, donc pas forcément à supprimer.

In [10]:
df.describe()

       achievements
count  12194.000000
mean      77.237494
std      448.501848
min        1.000000
25%       12.000000
50%       21.000000
75%       38.000000
max     9821.000000

## 11.Analyse de dates
On voit ici que `release_date` est du texte. Environ 1 590 valeurs ne sont pas de vraies dates comme par exemple TBA ou coming soon et 3 179 sont manquantes.

In [16]:
dates = pd.to_datetime(df["release_date"], format="%b %d, %Y", errors="coerce")
invalides = df.loc[dates.isna() & df["release_date"].notna(), "release_date"]
print(len(invalides))
invalides.value_counts().head(10)

1590

release_date
2019           296
Coming Soon    134
TBA             74
Summer 2019     68
2020            52
Coming soon     45
TBD             34
Jun 2019        33
Q3 2019         31
2018            28
Name: count, dtype: int64

## Constats de l'inspection

- Le jeu fait 40 833 lignes et 20 colonnes. On constate que toutes les colonnes sont du texte, les prix et les dates seront à convertir.
- Les manquants sont massifs dans certaines colonnes à plus de 60 % : la suppression, l'imputation ou le signalement sera à décider colonne par colonne, en justifiant chaque choix.
- La colonne `types` contient des bundles et des subs, et 83 noms sont en double : on sera amené à examiner cela au nettoyage (dans mon notebook 2).
- Enfin pour `release_date` il y a environ 1 590 valeurs qui ne sont pas de vraies dates et 3 179 valeurs manquantes. La conversion se fera également au nettoyage.